# Simple google cloud run deployment workflow

# TODO: this needs a better PR setup in the future
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  AZURE_REGISTRY: ${{secrets.AZURE_REGISTRY}}
  AZURE_REGISTRY_FE: ${{secrets.AZURE_REGISTRY}}/lr-frontend
  AZURE_REGISTRY_BE: ${{secrets.AZURE_REGISTRY}}/lr-backend
  FE_PROD_ENV_TEXT: ${{secrets.PROD_ENV_TS}}
  IS_PRODUCTION: true

jobs:
  frontend:
    name: Build and deploy the frontend
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: $AZURE_REGISTRY
          username: ${{secrets.AZURE_REGISTRY_USERNAME}}
          password: ${{secrets.AZURE_REGISTRY_PASSWORD}}
      - name: Build angular project
        run: |
          echo ${{FE_PROD_ENV_TEXT}} > frontend/src/environments/environment.prod.ts
          cd frontend
          npm ci
          npm run build:prod
      - name: Build docker image and push
        run: |
          cd frontend
          docker build . -t $AZURE_REGISTRY_FE:${{GITHUB_SHA}}
          docker push $AZURE_REGISTRY_FE:${{GITHUB_SHA}}
      - uses: azure/webapps-deploy@v2
        name: Deploy to azure
        with:
          app-name: ${{secrets.APP_NAME_FE}}
          images: $AZURE_REGISTRY_FE:${{GITHUB_SHA}}

  backend:
    name: Build and deploy the backend
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          login-server: $AZURE_REGISTRY
          username: ${{secrets.AZURE_REGISTRY_USERNAME}}
          password: ${{secrets.AZURE_REGISTRY_PASSWORD}}
      - name: Build graphql project
        run: |
          cd backend
          npm ci
          npm run build:prod
      - name: Build docker image and push
        run: |
          cd backend
          docker build . -t $AZURE_REGISTRY_BE:${{GITHUB_SHA}}
          docker push $AZURE_REGISTRY_BE:${{GITHUB_SHA}}

      - uses: azure/webapps-deploy@v2
        name: Deploy to azure
        with:
          app-name: ${{secrets.APP_NAME_BE}}
          images: $AZURE_REGISTRY_BE:${{GITHUB_SHA}}
